### PR TITLE
Move fonts to reduce bundle size

### PR DESCRIPTION
**Pull request by SamusElderg**
- moved the font files to the public folder
- changes the typography css rules to point to them so that they can be served as-is without being base64'd and added inline to style.css on build

This might solve a large portion of #15 but we should leave the issue open to tackle this a little deeper even if it does

image

### CODE REVIEW

**Comment by SamusElderg** [comment]
@leo95oliveira vercel isnt able to find the fonts in the public folder in the preview for some reason? This is specific to either vercel or storybook config as the build runs fine locally. Any ideas?

**Comment by leo95oliveira** [comment]
> @leo95oliveira vercel isnt able to find the fonts in the public folder in the preview for some reason? This is specific to either vercel or storybook config as the build runs fine locally. Any ideas?

Looking at the build logs on vercel, I think the issue is pertaining to Storybook. I'm not 100% sure but I'll take a look later this afternoon and see what I can find!

**Comment by SamusElderg** [comment]
@leo95oliveira fixed the issue with storybook (it was an issue with how absolute urls are handled) if you review this and its all good, should we bundle it in with the v2.0.0 release?

**Comment by leo95oliveira** [comment]
> @leo95oliveira fixed the issue with storybook (it was an issue with how absolute urls are handled) if you review this and its all good, should we bundle it in with the v2.0.0 release?

Legend! Looks great! Thank you for this! Yes, lets bundle it with v2!

**Comment by SamusElderg** [comment]
@leo95oliveira no rush, just checking if you intended to approve this one as your comments suggested you did but its still pending review 🙏

**Review by leo95oliveira — APPROVED** [review]
My apologies @SamusElderg! I thought I had already approved this 😭 thank you for tagging me

**Pull request merged**
