### PR TITLE
Add new icons

### PR DESCRIPTION
**Pull request by captainmangoC4**

### CODE REVIEW

**Review by SamusElderg — APPROVED** [review]
Oooo nice! Checked each icon by size and color all works great 👍

**Comment by SamusElderg** [comment]
hahah very sneaky adding a few more i see 😂 ill check them, actually i have a 'temporary' icon component in the .com repo too with notes to 'move them to component library' ill see if they are an easy add too, maybe not as i dont like the small/medium/large implementation and went for a integer (pixels) input for those i think

**Comment by SamusElderg** [comment]
all good! tested the dot/suggestion ones too!

**Comment by captainmangoC4** [comment]
> hahah very sneaky adding a few more i see 😂 

lol, I didn't expect you to review so soon!

**Comment by captainmangoC4** [comment]
> i dont like the small/medium/large implementation and went for a integer (pixels) input for those i think

We could change it to allow either s/m/l or pixels. We could just default to `size` in that switch statement where it translates size to pixels.

**Comment by SamusElderg** [comment]
> > i dont like the small/medium/large implementation and went for a integer (pixels) input for those i think
> 
> We could change it to allow either s/m/l or pixels. We could just default to `size` in that switch statement where it translates size to pixels.

Yeah i think an improvement would be to have the existing 3 string sizes and then optionally an integer to override it with a custom size, good idea! I just had a look at the code and the string is just translated to a pixel size anyway, so should be an easy change (we dont need to do it now though no immediate need)

Also i had a quick look at the casing of the properties are realised a little 'gotcha' i missed; react doesnt play well with non camelCase props even when they are inside a child svg.

So we will need to change anything like `fill-rule` and `clip-rule` into `fillRule` and `clipRule` to ensure once we are consuming the icons we dont have a fun amount of yelling in the console. I think ill make an eslint rule for this at some point as its a super easy one to overlook/forget

Ill make a list of search terms to search-replace below and edit if i find more to make the change easier when you get to it:
- `fill-rule`
- `clip-rule`
- WIP

**Comment by captainmangoC4** [comment]
Good catch! I'll fix those now; thanks Samus!

**Pull request merged**
